/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.app.ui.component;

import com.org.app.helper.SettingIconHelper;
import com.org.app.util.MouseHoverEffect;
import com.org.app.util.ScaleImageIconGenerator;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DoAnPanel extends javax.swing.JPanel {
    DoAnPanelModel doAnModel;;
    MenuDoAnPanel menuDAPanel;
    /**
     * Creates new form DoAnPanel
     */
    public DoAnPanel() {
        initComponents();
        setHoverForItem();
    }
    
    public DoAnPanel(MenuDoAnPanel menuDoAnPanel,DoAnPanelModel doAnModel){
        this();
        this.menuDAPanel = menuDoAnPanel;
        this.doAnModel = doAnModel;
        Dimension expectedDimension = new Dimension(80,96);
        this.setPreferredSize(expectedDimension);
        this.setMaximumSize(expectedDimension);
        this.setMinimumSize(expectedDimension);
        setUp();
    }
    
    public DoAnPanel(MenuDoAnPanel menuDoAnPanel,DoAnPanelModel doAnModel, Component parent) {
        this(menuDoAnPanel, doAnModel);
        
    }
    
    private void setUp() {
        lblTen.setText(doAnModel.getTenDA() + "(" + doAnModel.getKichCo() + ")");
        lblGia.setText(doAnModel.getGia().toString());
    }
    
    public void setAnh() {    
        lblAnh.setPreferredSize(new Dimension(40, 40));
        lblAnh.setMaximumSize(new Dimension(40, 40));
        lblAnh.setMinimumSize(new Dimension(40, 40));
//        System.out.println("1" + ScaleImageIconGenerator.class.getResource("/images/food_drink/douong_loai_icon.png"));
//        ImageIcon icon = new ImageIcon(ScaleImageIconGenerator.class.getResource("/images/food_drink/douong_loai_icon.png"));
//        System.out.println("icon: " + icon);
        SettingIconHelper.setIconFor(lblAnh, 40, 40, doAnModel.getAnh());
//        lblAnh.setIcon(icon);
    }
    
    private void setListenerForItem(Integer kcda_id){
        menuDAPanel.addItem(kcda_id);
    }
    
    private void setHoverForItem(){
        JLabel[] lbls = {lblAnh,lblGia,lblTen};
        for (int i = 0; i < lbls.length; i++) {
            MouseHoverEffect.mouseOverEffect_DA(Color.decode("#C9BAB2"), this, lbls[i]);
        }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnh = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnh.setMaximumSize(new java.awt.Dimension(24, 24));
        lblAnh.setPreferredSize(new java.awt.Dimension(24, 24));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên(S)");
        lblTen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenMouseClicked(evt);
            }
        });

        lblGia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGia.setText("Giá");
        lblGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        setListenerForItem(doAnModel.getId_kcda());
    }//GEN-LAST:event_formMouseClicked

    private void lblTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenMouseClicked
        // TODO add your handling code here:
        this.formMouseClicked(evt);
    }//GEN-LAST:event_lblTenMouseClicked

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        // TODO add your handling code here:
        this.formMouseClicked(evt);
    }//GEN-LAST:event_lblAnhMouseClicked

    private void lblGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaMouseClicked
        // TODO add your handling code here:
        this.formMouseClicked(evt);
    }//GEN-LAST:event_lblGiaMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        setHoverForItem();
    }//GEN-LAST:event_formMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblTen;
    // End of variables declaration//GEN-END:variables
}
