/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.app.ui.component;

import com.org.app.entity.SuatChieu;
import com.org.app.ui.quanly.TraCuuLichChieuFrame;
import com.org.app.util.CustomGridLayOut;
import com.org.app.util.FixedSizeCoatingPanel;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author intfs
 */
public class LichPhimPanel extends javax.swing.JPanel {
    int w;
    int h;
    List<SuatChieu> scNgay;
    List<LichPhimPanelComponent> list;
    private final int COLUMN_NUM = 2;
    /**
     * Creates new form PhongChieuLich
     */
    public LichPhimPanel(JPanel parent) {
        initComponents();
        w = parent.getWidth();
        scNgay = new ArrayList<>();
        list = new ArrayList<>();
        h = parent.getHeight();
        Dimension d = new Dimension(w,h);
        this.setPreferredSize(d);
        this.setMaximumSize(d);
        this.setMinimumSize(d);
    }
    
    public void setLichPhimList(List<SuatChieu> sc) {
        this.scNgay = sc;
        this.removeAll();
        showLich();
    }
    
    public void showLich() {
        list.clear();
        CustomGridLayOut layout = new CustomGridLayOut(scNgay.size(), COLUMN_NUM,10, 5);
        this.setLayout(layout.getLayOut());
        for (int i = 0; i < scNgay.size(); i++) {
            LichPhimPanelComponent comp = new LichPhimPanelComponent(scNgay.get(i),i);
            
            
            //
            this.add(coating(comp));
            list.add(comp);
        }
    }
    
    public List<LichPhimPanelComponent> getListComponents() {
        return list;
    }
 
   
    
    private JPanel coating (LichPhimPanelComponent comp) {
        return FixedSizeCoatingPanel.getCoatingJPanel(comp);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
