/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.app.ui.component;

import com.org.app.helper.DateHelper;
import com.org.app.helper.MessageHelper;
import com.org.app.helper.SettingIconHelper;
import com.org.app.ui.banhang.DatMenuFrame;
import com.org.app.ui.banhang.DatVeFrame;
import com.org.app.ui.main.MainFrame;
import com.org.app.util.FixedSizeCoatingPanel;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.LayoutManager;

/**
 *
 * @author intfs
 */
public class PhimPanel extends javax.swing.JPanel {
    private PhimPanelModel phimModel;
    MainFrame mainFrame;
    /**
     * Creates new form PhimPanel
     */
    public PhimPanel() {
        initComponents();

    }


    public PhimPanel(MainFrame mainF, PhimPanelModel phimModel) {
        this();
        mainFrame = mainF;
        this.phimModel = phimModel;
        Dimension expectedDimension = new Dimension(250,330);
        this.setPreferredSize(expectedDimension);
        this.setMaximumSize(expectedDimension);
        this.setMinimumSize(expectedDimension);;
        setUp();
        
    }
 
    
    public int getPanelWidth() {
        return this.getWidth();
    }
    public int getPanelHeight() {
        return this.getHeight();
    }
    
    
    private void setUp() {
        pnlSoVeBan.setBackground(new java.awt.Color(123,124,124,200));
        lblTen.setText(phimModel.getTenPhim());
        lblPhong.setText(setPhong(phimModel.getPhongChieu()));
        lblGio.setText(phimModel.getGioChieu());
        lblLuongVe.setText(String.valueOf(phimModel.getLuongVe())); 
        setToolTipThongTinPhim(phimModel.getTenPhim(), phimModel.getNgonNgu(), phimModel.getTheLoai(), phimModel.getNgayKC(), phimModel.getThoiLuong(), phimModel.getTrangThai());
        
    }
    public void setToolTipThongTinPhim(String tenPhim, String ngonNgu, String theLoai, java.sql.Date ngayKhoiChieu, int thoiLuong, String trangthai) {
        String t = String.format("<html>Tên: %s"
                + "<br>Ngôn ngữ: %s"
                + "<br>Thể loại: %s"
                + "<br>Ngày khởi chiếu: %s"
                + "<br>Thời lượng: %d phút"
                + "<br> Trạng thái: %s"
                + "</html>", 
                tenPhim, ngonNgu, theLoai, DateHelper.toString(ngayKhoiChieu), thoiLuong, trangthai);
        lblPoster.setToolTipText(t);
    }
    public void setPoster() {
//        System.out.println("width layr "+jLayeredPane1.getWidth());
        int w = 248;
        int h = 165;
        lblPoster.setPreferredSize(new Dimension(w, h));
        lblPoster.setMaximumSize(new Dimension(w, h));
        lblPoster.setMinimumSize(new Dimension(w, h));
//        System.out.println(phimModel.getPoster());
//        SettingIconHelper.setPosterFor(lblPoster, 214, 86, phimModel.getPoster());  
        SettingIconHelper.setPosterFor(lblPoster, w, h, phimModel.getPoster());  
    }
    
    private String setPhong(String idPhong) {
        return idPhong.replaceAll("(P[0]+?)(.+)$", "Phòng $2");
    }
    
    private void moveToBooking() {
//        MessageHelper.message(this, "move to datVeFrame");
        
//        DatVeFrame dv  = mainFrame.getFrame();
            mainFrame.showBooking(phimModel.getSc());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblPoster = new javax.swing.JLabel();
        gradientPanel2 = new com.org.app.customui.GradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblGio = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDatVe = new javax.swing.JButton();
        pnlSoVeBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLuongVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 233, 207));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102)));
        setMaximumSize(new java.awt.Dimension(250, 330));
        setMinimumSize(new java.awt.Dimension(250, 330));
        setPreferredSize(new java.awt.Dimension(250, 330));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(248, 165));
        jPanel2.setMinimumSize(new java.awt.Dimension(248, 165));
        jPanel2.setPreferredSize(new java.awt.Dimension(249, 165));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblPoster.setMaximumSize(new java.awt.Dimension(248, 165));
        lblPoster.setMinimumSize(new java.awt.Dimension(246, 165));
        lblPoster.setPreferredSize(new java.awt.Dimension(246, 165));
        jPanel2.add(lblPoster, java.awt.BorderLayout.CENTER);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 247, -1));

        gradientPanel2.setColor1(new java.awt.Color(240, 239, 229));
        gradientPanel2.setColor2(new java.awt.Color(229, 233, 207));
        gradientPanel2.setGradientFocus(130);
        gradientPanel2.setMaximumSize(new java.awt.Dimension(250, 150));
        gradientPanel2.setMinimumSize(new java.awt.Dimension(250, 150));
        gradientPanel2.setPreferredSize(new java.awt.Dimension(250, 150));

        jPanel4.setMaximumSize(null);
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 110));

        jLayeredPane2.setMaximumSize(new java.awt.Dimension(236, 25));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(236, 25));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGio.setBackground(new java.awt.Color(153, 153, 153));
        lblGio.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblGio.setForeground(new java.awt.Color(255, 255, 255));
        lblGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_clock_16px_2.png"))); // NOI18N
        lblGio.setText("11:20");
        lblGio.setOpaque(true);
        lblGio.setPreferredSize(new java.awt.Dimension(19, 25));
        jLayeredPane2.add(lblGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, -1));

        lblTen.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Gã điên");
        lblTen.setMaximumSize(new java.awt.Dimension(236, 35));
        lblTen.setMinimumSize(new java.awt.Dimension(236, 35));
        lblTen.setPreferredSize(new java.awt.Dimension(236, 35));

        lblPhong.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhong.setText("Phòng");
        lblPhong.setMaximumSize(new java.awt.Dimension(236, 16));
        lblPhong.setMinimumSize(new java.awt.Dimension(236, 16));
        lblPhong.setPreferredSize(new java.awt.Dimension(236, 16));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(236, 41));
        jPanel3.setMinimumSize(new java.awt.Dimension(236, 41));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(236, 40));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnDatVe.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnDatVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ticket_16px.png"))); // NOI18N
        btnDatVe.setText("Đặt vé");
        btnDatVe.setFocusable(false);
        btnDatVe.setIconTextGap(8);
        btnDatVe.setMaximumSize(new java.awt.Dimension(100, 40));
        btnDatVe.setMinimumSize(new java.awt.Dimension(100, 40));
        btnDatVe.setPreferredSize(new java.awt.Dimension(100, 40));
        btnDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatVeActionPerformed(evt);
            }
        });
        jPanel3.add(btnDatVe, java.awt.BorderLayout.EAST);

        pnlSoVeBan.setBackground(new java.awt.Color(123, 124, 124));
        pnlSoVeBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        pnlSoVeBan.setMaximumSize(new java.awt.Dimension(90, 40));
        pnlSoVeBan.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số vé bán");
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 20));

        lblLuongVe.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        lblLuongVe.setForeground(new java.awt.Color(255, 255, 255));
        lblLuongVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLuongVe.setText("10");
        lblLuongVe.setMaximumSize(new java.awt.Dimension(90, 20));
        lblLuongVe.setMinimumSize(new java.awt.Dimension(90, 20));
        lblLuongVe.setPreferredSize(new java.awt.Dimension(90, 20));

        javax.swing.GroupLayout pnlSoVeBanLayout = new javax.swing.GroupLayout(pnlSoVeBan);
        pnlSoVeBan.setLayout(pnlSoVeBanLayout);
        pnlSoVeBanLayout.setHorizontalGroup(
            pnlSoVeBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblLuongVe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSoVeBanLayout.setVerticalGroup(
            pnlSoVeBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoVeBanLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblLuongVe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(pnlSoVeBan, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout gradientPanel2Layout = new javax.swing.GroupLayout(gradientPanel2);
        gradientPanel2.setLayout(gradientPanel2Layout);
        gradientPanel2Layout.setHorizontalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        gradientPanel2Layout.setVerticalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 169, 247, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatVeActionPerformed
        moveToBooking();
    }//GEN-LAST:event_btnDatVeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatVe;
    private com.org.app.customui.GradientPanel gradientPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblLuongVe;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblTen;
    private javax.swing.JPanel pnlSoVeBan;
    // End of variables declaration//GEN-END:variables
}
