/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.app.ui.component;

import com.org.app.entity.PhongChieu;
import com.org.app.helper.DateHelper;
import com.org.app.helper.TimeHelper;
import com.org.app.ui.main.MainFrame;
import com.org.app.ui.quanly.QLSuatChieuFrame;
import com.org.app.ui.quanly.TraCuuLichChieuFrame;
import com.org.app.util.LabelWrapperInterface;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author intfs
 */
public class PhongPanel extends javax.swing.JPanel implements LabelWrapperInterface{
    public String pc;
    private Integer[] luongSuat;
    private List<Object[]> listTop3;
    private MainFrame mainFrame;
    private JLabel[][] lbls;
    /**
     * Creates new form PhongPanel
     */
    public PhongPanel(String pc) {
        initComponents();
        luongSuat = new Integer[] {0,0}; 
        
        this.pc = pc;
        listTop3 = new ArrayList<>();
        lbls = new JLabel[][] {{lblSuat1, lblGio1}, {lblSuat2, lblGio2}, {lblSuat3, lblGio3}};
        setLabels();
    }
    
    
    public void setLuongSuatChieu(Integer[] ls,  List<Object[]> top3) {
        luongSuat = ls;
        lblLuongSuat.setText(gettLuongSuat());
        
        listTop3 = top3;
        clear();
        setTop3();
    }
    
    public PhongPanel(String pc, MainFrame main) {
        this(pc);
        mainFrame = main;
    }
    
    public void setTop3() {
        for (int i = 0; i < listTop3.size(); i++) {
            Object[] o = listTop3.get(i);
            for (int j = 0; j < lbls[i].length; j++) {
                setSuatLabel(lbls[i][0], o[1].toString());
                setGioOfSuatLabel(lbls[i][1], o[2]);
            }
            
        }
    }
    
    private void clear() {
        for (int i = 0; i < lbls.length; i++) {
            for (int j = 0; j < lbls[i].length; j++) {
                lbls[i][j].setText("");
            }
            
        }
    }
    
    public void setSuatLabel(JLabel lbl, String txt) {
        wrap(lbl,txt);
    }
    
    public void setGioOfSuatLabel(JLabel lbl, Object time) {
        Time t = (Time) time;
        wrap(lbl, TimeHelper.toStringWithHourMintues(t));
    }
    public void setLabels() {
        lblPhong.setText(getTenPhong());
        lblLuongSuat.setText(gettLuongSuat());;
    }
    
    private String gettLuongSuat() {
       return String.format("Đã chiếu: %d/%d  ", luongSuat[0], luongSuat[1]);
    }
    
    private String getTenPhong() {
        System.out.println("ten phong = "+ pc);
        int p = Integer.parseInt(pc.substring(1, pc.length()));
        String tp = "Phòng ";
        if( p < 10) return tp + "0" + p;
        else return tp + p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedGradientPanel1 = new com.org.app.customui.RoundedGradientPanel();
        btnTraLich = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblSuat1 = new javax.swing.JLabel();
        lblGio1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblSuat2 = new javax.swing.JLabel();
        lblGio2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblSuat3 = new javax.swing.JLabel();
        lblGio3 = new javax.swing.JLabel();
        pnlPhongTitle = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel();
        lblLuongSuat = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(275, 210));
        setPreferredSize(new java.awt.Dimension(275, 210));
        setLayout(new java.awt.BorderLayout());

        roundedGradientPanel1.setBorderRadius(0.3F);
        roundedGradientPanel1.setColor1(new java.awt.Color(201, 213, 225));
        roundedGradientPanel1.setColor2(new java.awt.Color(177, 223, 223));
        roundedGradientPanel1.setMaximumSize(new java.awt.Dimension(275, 210));
        roundedGradientPanel1.setPreferredSize(new java.awt.Dimension(275, 210));

        btnTraLich.setText("Tra lịch");
        btnTraLich.setPreferredSize(new java.awt.Dimension(100, 23));
        btnTraLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLichActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(214, 234, 250));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(255, 110));
        jPanel1.setMinimumSize(new java.awt.Dimension(255, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(255, 110));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 0, 1));

        jPanel4.setBackground(new java.awt.Color(255,255,255,100));
        jPanel4.setMaximumSize(new java.awt.Dimension(255, 30));
        jPanel4.setOpaque(false);

        lblSuat1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblSuat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_movie_projector_24px_1.png"))); // NOI18N
        lblSuat1.setText("jLabel2");
        lblSuat1.setMaximumSize(new java.awt.Dimension(185, 30));
        lblSuat1.setMinimumSize(new java.awt.Dimension(185, 30));
        lblSuat1.setPreferredSize(new java.awt.Dimension(185, 30));

        lblGio1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblGio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio1.setText("jLabel2");
        lblGio1.setMaximumSize(new java.awt.Dimension(70, 30));
        lblGio1.setMinimumSize(new java.awt.Dimension(70, 30));
        lblGio1.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuat1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblGio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuat1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblGio1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel4);

        jPanel6.setMaximumSize(new java.awt.Dimension(255, 30));
        jPanel6.setOpaque(false);

        lblSuat2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblSuat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_movie_projector_24px_1.png"))); // NOI18N
        lblSuat2.setText("jLabel2");
        lblSuat2.setMaximumSize(new java.awt.Dimension(185, 30));
        lblSuat2.setMinimumSize(new java.awt.Dimension(185, 30));
        lblSuat2.setPreferredSize(new java.awt.Dimension(185, 30));

        lblGio2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblGio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio2.setText("jLabel2");
        lblGio2.setMaximumSize(new java.awt.Dimension(70, 30));
        lblGio2.setMinimumSize(new java.awt.Dimension(70, 30));
        lblGio2.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuat2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblGio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuat2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblGio2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel6);

        jPanel5.setMaximumSize(new java.awt.Dimension(255, 30));
        jPanel5.setOpaque(false);

        lblSuat3.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblSuat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_movie_projector_24px_1.png"))); // NOI18N
        lblSuat3.setText("jLabel2");
        lblSuat3.setMaximumSize(new java.awt.Dimension(185, 30));
        lblSuat3.setMinimumSize(new java.awt.Dimension(185, 30));
        lblSuat3.setPreferredSize(new java.awt.Dimension(185, 30));

        lblGio3.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        lblGio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio3.setText("jLabel2");
        lblGio3.setMaximumSize(new java.awt.Dimension(70, 30));
        lblGio3.setMinimumSize(new java.awt.Dimension(70, 30));
        lblGio3.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuat3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblGio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuat3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblGio3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel5);

        pnlPhongTitle.setBackground(new java.awt.Color(255, 204, 153));
        pnlPhongTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        pnlPhongTitle.setMaximumSize(new java.awt.Dimension(275, 33));
        pnlPhongTitle.setMinimumSize(new java.awt.Dimension(275, 33));
        pnlPhongTitle.setOpaque(false);
        pnlPhongTitle.setPreferredSize(new java.awt.Dimension(275, 33));

        lblPhong.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_theatre_curtain_24px.png"))); // NOI18N
        lblPhong.setText("Phòng");
        lblPhong.setMaximumSize(new java.awt.Dimension(150, 25));
        lblPhong.setMinimumSize(new java.awt.Dimension(150, 25));
        lblPhong.setPreferredSize(new java.awt.Dimension(150, 25));

        lblLuongSuat.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblLuongSuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLuongSuat.setText("Đã chiếu: 3/4");
        lblLuongSuat.setToolTipText("Số suất đã chiếu");
        lblLuongSuat.setMaximumSize(new java.awt.Dimension(91, 25));
        lblLuongSuat.setMinimumSize(new java.awt.Dimension(91, 25));
        lblLuongSuat.setOpaque(true);
        lblLuongSuat.setPreferredSize(new java.awt.Dimension(91, 25));

        javax.swing.GroupLayout pnlPhongTitleLayout = new javax.swing.GroupLayout(pnlPhongTitle);
        pnlPhongTitle.setLayout(pnlPhongTitleLayout);
        pnlPhongTitleLayout.setHorizontalGroup(
            pnlPhongTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhongTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLuongSuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlPhongTitleLayout.setVerticalGroup(
            pnlPhongTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhongTitleLayout.createSequentialGroup()
                .addGroup(pnlPhongTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuongSuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedGradientPanel1Layout = new javax.swing.GroupLayout(roundedGradientPanel1);
        roundedGradientPanel1.setLayout(roundedGradientPanel1Layout);
        roundedGradientPanel1Layout.setHorizontalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnTraLich, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addComponent(pnlPhongTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedGradientPanel1Layout.setVerticalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPhongTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTraLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(roundedGradientPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLichActionPerformed
        mainFrame.showCard(TraCuuLichChieuFrame.CARD_NAME_MAIN);
        ((TraCuuLichChieuFrame)mainFrame.getCurrentFrame()).setFilterPhong(pc, DateHelper.now(), DateHelper.now());
    }//GEN-LAST:event_btnTraLichActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraLich;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblGio1;
    private javax.swing.JLabel lblGio2;
    private javax.swing.JLabel lblGio3;
    private javax.swing.JLabel lblLuongSuat;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSuat1;
    private javax.swing.JLabel lblSuat2;
    private javax.swing.JLabel lblSuat3;
    private javax.swing.JPanel pnlPhongTitle;
    private com.org.app.customui.RoundedGradientPanel roundedGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
