/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.app.ui.intro;

import com.org.app.helper.SettingIconHelper;
import com.org.app.ui.login.LoginFrame;
import com.org.app.ui.main.MainFrame;
import com.org.app.util.ColorAndIconBank;
import com.org.app.util.ScaleImageIconGenerator;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author intfs
 */
public class IntroFrame extends javax.swing.JFrame {

    Timer t;
    static final int MAX = 100;
    static int MIN = 0;
    MainFrame main;

    /**
     * Creates new form IntorFrame
     */
    public IntroFrame() {
        initComponents();
        this.setIconImage(new ImageIcon(MainFrame.class.getResource("/icon/boot_noSologan.png")).getImage());
        SettingIconHelper.setIconSourceFor(lblBackground, "intro_bckg.png");
        setLocationRelativeTo(null);

        loading();

    }
  
    private void loading() {
        t = new Timer(250, new ActionListener() {
            int count = 1;
            @Override
            public void actionPerformed(ActionEvent e) {
                if (MIN >= MAX) {
//                if (MainFrame.isDone) {
                    t.setRepeats(false);
                    t.stop();
                    openLoginFrame();
                }
                MIN += 6;
                String strLoad = "";

                if (count == 6) {
                    count = 0;
                }

                //strLoad = "";
                for (int i = 1; i <= count; i++) {
                    strLoad += ".";
                }
                lblDot.setText(strLoad);
                count++;
            }
        });

        t.start();
    }

    private void openLoginFrame() {
        this.dispose();
        new LoginFrame().setVisible(true);
//        main.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDot = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDot.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblDot.setText("...");
        getContentPane().add(lblDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 60, 20));

        lblLoading.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblLoading.setText("Loading");
        getContentPane().add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 20));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDot;
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables

}
